# Node JS
#FROM 24-alpine3.21

# Make NewForlder in Docker
#WORKDIR /app/web


# Copy Code | From... -> To...
# From:  folder hiện tại trong PC -> To:  folder trong Docker
# VD: Copy tất cả file vào folder /app/web
#COPY . /app/web

# install lib (run in Terminal)
#RUN npm i

# Expose port của docker
#PORT 5173:5173
#EXPOSE 5173

# Run app (run Project)
#CMD ["npm", "run", "dev"]