#1. Image NODE JS -> dockerHub
FROM node:24-alpine3.21

#2 Make New Folder in Docker
WORKDIR /app/web

#3 Copy code | From ... -> To ...
# From: folder hiện tại trong PC -> To:  folder trong Docker
# VD: Copy tất cả file vào folder /app/web
#COPY . /app/web

#4 import library (run in Terminal)
#RUN npm i

#5 Anh xa Port
#PORT 5173:5173
#EXPOSE 5173

#6 Run app (run Project)
#CMD ["npm", "run", "dev"]
