/* Tạo ngân hàng câu hỏi */
const questions = [
    {
        id: 1,
        question: 'How are you today????',
        a: 'ahmm',
        b: 'Uhm',
        c: 'Good',
        d: 'Cook',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 2,
        question: 'What is the capital of France?',
        a: 'London',
        b: 'Paris',
        c: 'Berlin',
        d: 'Madrid',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 3,
        question: 'Which planet is known as the Red Planet?',
        a: 'Earth',
        b: 'Mars',
        c: 'Venus',
        d: 'Jupiter',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 4,
        question: 'What is 2 + 2?',
        a: '3',
        b: '4',
        c: '5',
        d: '22',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 5,
        question: 'What color do you get when you mix red and blue?',
        a: 'Purple',
        b: 'Orange',
        c: 'Green',
        d: 'Pink',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 6,
        question: 'What is the largest mammal?',
        a: 'Elephant',
        b: 'Blue Whale',
        c: 'Giraffe',
        d: 'Rhino',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 7,
        question: 'Which continent is Egypt located in?',
        a: 'Africa',
        b: 'Asia',
        c: 'Europe',
        d: 'Australia',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 8,
        question: 'What is the boiling point of water?',
        a: '90°C',
        b: '100°C',
        c: '120°C',
        d: '80°C',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 9,
        question: 'Which animal is known as the king of the jungle?',
        a: 'Tiger',
        b: 'Elephant',
        c: 'Lion',
        d: 'Bear',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 10,
        question: 'What gas do plants use for photosynthesis?',
        a: 'Oxygen',
        b: 'Hydrogen',
        c: 'Carbon Dioxide',
        d: 'Nitrogen',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 11,
        question: 'What shape has three sides?',
        a: 'Circle',
        b: 'Triangle',
        c: 'Square',
        d: 'Rectangle',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 12,
        question: 'Which season comes after summer?',
        a: 'Winter',
        b: 'Autumn',
        c: 'Spring',
        d: 'Rainy',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 13,
        question: 'What color is the sky on a clear day?',
        a: 'Blue',
        b: 'Red',
        c: 'Green',
        d: 'Yellow',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 14,
        question: 'Which sense do we use to smell?',
        a: 'Sight',
        b: 'Touch',
        c: 'Hearing',
        d: 'Smell',
        correctAns: 'd',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 15,
        question: 'How many legs does a spider have?',
        a: '6',
        b: '8',
        c: '10',
        d: '12',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 16,
        question: 'What do bees produce?',
        a: 'Milk',
        b: 'Wax',
        c: 'Honey',
        d: 'Oil',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 17,
        question: 'How many days are there in a leap year?',
        a: '364',
        b: '365',
        c: '366',
        d: '360',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 18,
        question: 'What do we call a baby dog?',
        a: 'Cub',
        b: 'Kitten',
        c: 'Puppy',
        d: 'Chick',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 19,
        question: 'Which ocean is the largest?',
        a: 'Atlantic',
        b: 'Indian',
        c: 'Arctic',
        d: 'Pacific',
        correctAns: 'd',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 20,
        question: 'What is H2O commonly known as?',
        a: 'Salt',
        b: 'Water',
        c: 'Hydrogen',
        d: 'Oxygen',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    }
];

export {questions}